### ISSUE TITLE
Is anything here up to date?

### ISSUE THREAD

**Issue by gabsillis** [robodogs435frc/2016Code#19]
From what I see looking through so far there are two drive motors set up with arcade drive in teleoperated, but use tank drive values in the commands. This does not seem like an initial working release, which is critical now because the mechanical subdivisions are wrapping up sections of the robot and most of the wiring is ready.

**Comment by adamsong** [comment]
Pull requests #17 and #18 are pending approval.

**Comment by adamsong** [comment]
Yes, pull requests merged.
